language: node_js
node_js:
  - "11"
install:
  - npm install -g nyc
  - npm install -g codecov
  - npm install
script:
  - nyc npm run linux-mocha
  - nyc report --reporter=text-lcov > coverage.lcov
  - codecov